apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: argocd-private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository  # This label is required for Argo CD to recognize this secret as a repository credential.
stringData:
  type: git
  url: git@github.com:devjerry04/test_application.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5v
    -----END  
#  This is your SSH private key from your PC
# (the same one you use for GitHub SSH access)