apiVersion: v1
kind: Secret
metadata:
  name: external
  labels:
    argocd.argoproj.io/secret-type: cluster  #important to add cluster 
type: Opaque
stringData:
  name: external
  server: API_SERVER_ADDRESS  #in kube config file 
  config: |
    {
      "bearerToken": "SERVICE_ACCOUNT_TOKEN",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "BASE64 ENCODED CERTIFICATE"  #ca.crt file content 
      }
    }